---
title: "flat_ecoscope_palette.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Ecoscope custom color palette

Create a custom color palette to be used for plotting results from the above functions. The function uses a color palette matching the EcoScope project graphic templates. 

```{r function-ecoscope_palette}
#' Color palettes
#'
#' @export
ecoscope_palette <- list(
  `ecoscope1` = c("black","#89a3ab", "#8bcde6", "#21647d", "#3859ea", "#28a1d2", "#28ccd3",
                  "#98cb48", "#7f8e53", "#b6bbaf", "#8b7454", "#ece8dc", "#cdba9b", "#c3703a",
                  "#ea985c", "#fd655b", "#cc3118", "#8f0405", "#8e375a", "#aa34a7", "#e01edb", "#781576")
)


#' Function to interpolate a color palette
#'
#' @param palette Character name of palette in ecoscope_palette
#' @param reverse Boolean true if palette should be reversed
#' @param ... Additional arguments to pass to colorRampPalette()
#' @export
ecoscope_pal <- function(palette = "ecoscope1", reverse = FALSE, ...){
  pal <- ecoscope_palette[[palette]]
  
  if(reverse){
    pal <- rev(pal)
  }
  
  grDevices::colorRampPalette(pal, ...)
}

#' Color scale for Ecoscope colors
#'
#' @param palette Character name of palette in ecoscope_palette
#' @param discrete Boolean if color aesthetic is discrete
#' @param reverse Boolean indicating whether palette should be reversed
#' @param ... Additional arguments used to discrete_scale() or scale_fill_gradientn()
#'   to automatically interpolate between colours.
#' @export
scale_color_ecoscope <- function(palette = "ecoscope1",
                                discrete = TRUE, reverse=FALSE,...){
  pal <- ecoscope_pal(palette = palette, reverse = reverse)
  
  if(discrete){
    ggplot2::discrete_scale("colour", paste0("ecoscope_", palette), palette = pal, ...)
  }else{
    ggplot2::scale_color_gradientn(colours = pal(256), ...)
  }
}

#' Fill scale for Ecoscope colors
#'
#' @param palette Character name of palette in ecoscope_palette
#' @param discrete Boolean if color aesthetic is discrete
#' @param reverse Boolean if palette should be reversed
#' @param ... Additional arguments used to discrete_scale() or scale_fill_gradientn()
#'   to automatically interpolate between colours.
#' @export
scale_fill_ecoscope <- function(palette = "ecoscope1",
                               discrete = TRUE, reverse = FALSE, ...){
  pal <- ecoscope_pal(palette = palette, reverse = reverse)
  
  if(discrete){
    ggplot2::discrete_scale("fill", paste0("ecoscope_", palette), palette = pal, ...)
  }else{
    ggplot2::scale_fill_gradientn(colours = pal(256),...)
  }
}
```


```{r examples-ecoscope_palette}
ggplot2::ggplot(diet) +
  ggplot2::geom_col(ggplot2::aes(x = Predator_key, y = pW, fill = Functional_group)) +
  scale_fill_ecoscope() 
```


```{r tests-ecoscope_palette}
test_that("scale_color_ecoscope works", {
  expect_true(inherits(scale_color_ecoscope, "function")) 
})
```
  


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_ecoscope_palette.Rmd", vignette_name = NA) # will not generate a vignette
```

