# WARNING - Generated by {fusen} from dev/flat_bioconsest.Rmd: do not edit by hand

#' Estimating energyscape and biomass consumption with Monte Carlo simulations
#'
#' Function to run the Monte Carlo simulation for energyscape and biomass estimations. This functions identifies the prey levels as defined by the prey_taxonomic_level, drop any item for which pW or Energy_content is missing, runs the \code{\link{bio_cons_est}} function n_sim times for each item, extracts the posterior distributions of each estimated parameter and returns the summarized results for all levels in prey_taxonomic_level. The function also provides a facility to estimate biomass consumption only for depth accessible to the predator: this is done by switching `mask_bathy` to yes, which will put to zero all predator abundance at depth larger than the provided `diving_depth`, but only for the prey groups specified in `groups_to_mask`. This may be useful when some prey groups (e.g. benthic species) are only accessible in some areas (e.g. continental shelf). 
#'  
#' @importFrom glue glue
#' @importFrom dplyr mutate summarize select rename pull case_when
#' @importFrom tidyselect contains any_of
#' @importFrom tidyr drop_na
#' @importFrom purrr map
#' @importFrom assertthat assert_that '%has_name%'
#' 
#' @param nsim The number of simulations to run; 1000 by default
#' @param map_coordinates data.frame containing x and y coordinates of the map
#' @param mask_bathy character. "yes" or "no" (default). If yes, the abundance layer will be masked based on diving depth of the predator before estimating the biomass consumpion for prey groups provided in `groups_to_mask`. 
#' @param bathy_col character. The name of the column in `abundance_map` where bathymetry information is stored. Used only if `mask_bathy == yes`.
#' @param diving_depth numeric. Diving depth of the predator (provided as positive number). Used only if `mask_bathy == yes`. 
#' @param groups_to_mask character vector. A vector containing the prey groups (as found in `diet`) for which the masking must be done. Used only if `mask_bathy == yes`.
#' @inheritParams bio_cons_est
#' 
#' @return  The function returns a list of 8 elements: FMR_map, the map of FMR (kJ/d); Energyscape_map, the energyscape map (kJ/d; FMR * abundance), with the abundance of the species (columns named N_); DailyRation_map, the map of daily ration (kg); DailyRationPropBM_map, the same but as proportion of body mass; DailyRation, the estimated daily ration averaged over the map (as a table; in kg); DailyRationPropBM, the same as proportion of body mass; Conso_map, the map of total consumed biomass (in kg) and Conso, the consumed biomass summed over the map (in kg). When more than one category exists for a prey_taxonomic_level, maps are returned as tables in a long format (directly usable with facetting in ggplot), except for FMR and Energyscape which return the maps estimated with the first category (for these two elements, the result is the same with any prey_group).
#' 
#' 
#' @export
#'
#' @examples
#' # test mc_simulation() with one prey level
#' TURTRU_result <- mc_simulation(predator_name = "TURTRU", 
#'                                predator_group = "Cetacean",
#'              map_coordinates = map_coords,
#'              prey_taxonomic_level = "Taxonomic_group", 
#'              diet = diet |> subset(Taxonomic_group == "Cephalopoda"), 
#'              assimilation_rate = 0.8,
#'              n_days = 30+31+31,
#'              predator_weight = weight, 
#'              abundance_map = species_abundance, 
#'              temperature_map = sst, # not used for cetaceans and seabirds
#'              beta = beta)
#'
#' # test mc_simulation() with 2 prey levels
#' TURTRU_result <- mc_simulation(predator_name = "TURTRU", 
#'                                predator_group = "Cetacean",
#'              map_coordinates = map_coords,
#'              prey_taxonomic_level = "Taxonomic_group", 
#'              diet = diet, 
#'              assimilation_rate = 0.8,
#'              n_days = 30+31+31,
#'              predator_weight = weight, 
#'              abundance_map = species_abundance, 
#'              temperature_map = sst, # not used for cetaceans and seabirds
#'              beta = beta)
#'
#' # plot results
#' ggplot2::ggplot(TURTRU_result$Conso) +
#'     ggplot2::geom_pointrange(ggplot2::aes(y = Prey_category, x = mean, xmin = L10, xmax = U90))
#'
#' ggplot2::ggplot(TURTRU_result$Energyscape) +
#'   ggplot2::geom_tile(ggplot2::aes(x = x, y = y, fill = Energyscape_mean))
#'
#'
mc_simulation <- function(predator_name, 
                          predator_group, 
                       map_coordinates,
                       beta = NULL,
                       prey_taxonomic_level, 
                       diet, 
                       assimilation_rate = 0.8, 
                       n_days = 1,
                       predator_weight, # en kg
                       abundance_map, 
                       temperature_map = NULL,
                       nsim = 1000,
                       mask_bathy = "no",
                       bathy_col = NULL,
                       groups_to_mask = NULL,
                       diving_depth = NULL){
  # check map_coords
  assert_that(map_coordinates %has_name% c("x", "y"))
  if(mask_bathy == "yes" & any(is.null(bathy_col), is.null(groups_to_mask), is.null(diving_depth))){
    stop("If mask_bathy == yes, bathy_col, groups_to_mask and diving_depth must all be provided")
  }
  if(mask_bathy == "yes" & isFALSE(all( groups_to_mask %in% (diet |> dplyr::pull(prey_taxonomic_level))))){
    stop(glue("Not all groups in groups_to_mask are present in {prey_taxonomic_level} in {diet}"))
  }
  if(mask_bathy == "yes" & isFALSE(length(diving_depth) == 1)) { stop("diving_depth must be of length 1") }
  
  # extract the prey category in the requested taxonomic level ----
  diet <- diet |> tidyr::drop_na(tidyselect::any_of(c("pW", "Energy_content", prey_taxonomic_level)))
  levels <- unique(dplyr::pull(diet, prey_taxonomic_level))
  if(length(levels) == 0) {
    stop(glue::glue("No prey categories in {prey_taxonomic_level} for {predator_name}"))
  }
  if(length(levels) == 1) {
    # Run the simulation
    MC_sim <- pbapply::pblapply(1:nsim, function(i){
      if(mask_bathy == "yes" & 
         levels %in% groups_to_mask){
        abundance_map <- abundance_map |> dplyr::mutate(
          mean = dplyr::case_when( .data[[bathy_col]] < (-diving_depth) ~ 0, TRUE ~ mean ),
          sd = dplyr::case_when( .data[[bathy_col]] < (-diving_depth) ~ 0, TRUE ~ sd )
          )
      }
      toto <- bio_cons_est(predator_name = predator_name, 
                           predator_group = predator_group,
                 prey_taxonomic_level = prey_taxonomic_level, 
                 prey_group = levels,
                 diet = diet, 
                 assimilation_rate = assimilation_rate,
                 n_days = n_days,
                 predator_weight = predator_weight, 
                 abundance_map = abundance_map, 
                 temperature_map = temperature_map,
                 beta = beta)
    })
  
    # Extract and format the results
    ## FMR
    posterior_FMR <- MC_sim |> 
      purrr::map(`[[`, "FMR") |> # ou purrr::map(`[[`, 1)
      do.call(what = "cbind") # a map array for fish, a vector for others
    
    smry_FMR_map <- data.frame(
      x = map_coordinates$x,
      y = map_coordinates$y,
      FMR_mean = apply( posterior_FMR, 1, "mean"),
      FMR_sd = apply( posterior_FMR, 1, "sd"),
      FMR_L10 = apply( posterior_FMR, 1, function(i){quantile(i, probs = 0.10)}),
      FMR_U90 = apply( posterior_FMR, 1, function(i){quantile(i, probs = 0.90)}),
      Prey_category = levels,
      Predator_key = predator_name
    )
    
    ## Abundance and energyscapes
    posterior_ab <- MC_sim |> 
      purrr::map(`[[`, "abundance") |> # ou purrr::map(`[[`, 1)
      do.call(what = "cbind") # a map array for fish, a vector for others
    
    posterior_Energyscape <- MC_sim |> 
      purrr::map(`[[`, "Energyscape") |>
      do.call(what = "cbind") # an map array
    
    smry_Energyscape <- data.frame(
      x = map_coordinates$x,
      y = map_coordinates$y,
      N_mean = apply( posterior_ab, 1, "mean"),
      N_sd = apply( posterior_ab, 1, "sd"),
      N_L10 = apply( posterior_ab, 1, function(i){quantile(i, probs = 0.10)}),
      N_U90 = apply( posterior_ab, 1, function(i){quantile(i, probs = 0.90)}),
      Energyscape_mean = apply( posterior_Energyscape, 1, "mean"),
      Energyscape_sd = apply( posterior_Energyscape, 1, "sd"),
      Energyscape_L10 = apply( posterior_Energyscape, 1, function(i){quantile(i, probs = 0.10)}),
      Energyscape_U90 = apply( posterior_Energyscape, 1, function(i){quantile(i, probs = 0.90)}),
      Prey_category = levels,
      Predator_key = predator_name
    )
    
    ## Daily ration
    posterior_Ration <- MC_sim |> 
      purrr::map(`[[`, "daily_ration") |>
      do.call(what = "cbind") # a map array for fish, a vector for the others
    
    smry_Ration_map <- data.frame(
      x = map_coordinates$x,
      y = map_coordinates$y,
      Ration_mean = apply( posterior_Ration, 1, "mean"),
      Ration_sd = apply( posterior_Ration, 1, "sd"),
      Ration_L10 = apply( posterior_Ration, 1, function(i){quantile(i, probs = 0.10)}),
      Ration_U90 = apply( posterior_Ration, 1, function(i){quantile(i, probs = 0.90)}),
      Prey_category = levels,
      Predator_key = predator_name
    )
    
    smry_Ration <- data.frame(
      mean = mean(smry_Ration_map$Ration_mean),
      sd = mean(smry_Ration_map$Ration_sd),
      L10 = quantile(smry_Ration_map$Ration_L10, probs = 0.10),
      U90 = quantile(smry_Ration_map$Ration_U90, probs = 0.90),
      Prey_category = levels,
      Predator_key = predator_name
    )
    
    ## Daily ration prop body mass
    posterior_RationPropBM <- MC_sim |> 
      purrr::map(`[[`, "prop_body_mass") |>
      do.call(what = "cbind")
    
    smry_RationPropBM_map <- data.frame(
      x = map_coordinates$x,
      y = map_coordinates$y,
      RationPropBM_mean = apply( posterior_RationPropBM, 1, "mean"),
      RationPropBM_sd = apply( posterior_RationPropBM, 1, "sd"),
      RationPropBM_L10 = apply( posterior_RationPropBM, 1, function(i){quantile(i, probs = 0.10)}),
      RationPropBM_U90 = apply( posterior_RationPropBM, 1, function(i){quantile(i, probs = 0.90)}),
      Prey_category = levels,
      Predator_key = predator_name
    )
    
    smry_RationPropBM <- data.frame(
      mean = mean(smry_RationPropBM_map$RationPropBM_mean),
      sd = mean(smry_RationPropBM_map$RationPropBM_sd),
      L10 = quantile(smry_RationPropBM_map$RationPropBM_L10, probs = 0.10),
      U90 = quantile(smry_RationPropBM_map$RationPropBM_U90, probs = 0.90),
      Prey_category = levels,
      Predator_key = predator_name
    )
    
    # ConsoMap
    posterior_ConsoMap <- MC_sim |> 
      purrr::map(`[[`, "conso_map") |>
      do.call(what = "cbind")
    
    smry_ConsoMap_map <- data.frame(
      x = map_coordinates$x,
      y = map_coordinates$y,
      ConsoMap_mean = apply( posterior_ConsoMap, 1, "mean"),
      ConsoMap_sd = apply( posterior_ConsoMap, 1, "sd"),
      ConsoMap_L10 = apply( posterior_ConsoMap, 1, function(i){quantile(i, probs = 0.10)}),
      ConsoMap_U90 = apply( posterior_ConsoMap, 1, function(i){quantile(i, probs = 0.90)}),
      Prey_category = levels,
      Predator_key = predator_name
    )
    
    smry_ConsoMap <- data.frame(
      mean = sum(smry_ConsoMap_map$ConsoMap_mean),
      sd = sum(smry_ConsoMap_map$ConsoMap_sd),
      L10 = sum(smry_ConsoMap_map$ConsoMap_L10),
      U90 = sum(smry_ConsoMap_map$ConsoMap_U90),
      Prey_category = levels,
      Predator_key = predator_name
    )
    
    # return the result tables
    return(list(
      FMR_map = smry_FMR_map, 
      Energyscape = smry_Energyscape, 
      DailyRation_map = smry_Ration_map, 
      DailyRation = smry_Ration, 
      DailyRationPropBM_map = smry_RationPropBM_map, 
      DailyRationPropBM = smry_RationPropBM, 
      Conso_map = smry_ConsoMap_map, 
      Conso = smry_ConsoMap
    ))
  }
  if(length(levels) > 1){
    # compute mc_sim for each level separately
    prey_loop <- lapply(1:length(levels), function(i){
      message(paste0("Computing ", levels[i], " for ", predator_name))
      # check if musk mask on diving depth for this level
      if(mask_bathy == "yes" & 
         levels[i] %in% groups_to_mask){
        abundance_map <- abundance_map |> dplyr::mutate(
          mean = dplyr::case_when( .data[[bathy_col]] < (-diving_depth) ~ 0, TRUE ~ mean ),
          sd = dplyr::case_when( .data[[bathy_col]] < (-diving_depth) ~ 0, TRUE ~ sd )
          )
      }
      
      # Run the simulation
      MC_sim <- pbapply::pblapply(1:nsim, function(j){
        toto <- bio_cons_est(predator_name = predator_name, 
                           predator_group = predator_group,
                 prey_taxonomic_level = prey_taxonomic_level, 
                 prey_group = levels[i],
                 diet = diet, 
                 assimilation_rate = assimilation_rate,
                 n_days = n_days,
                 predator_weight = predator_weight, 
                 abundance_map = abundance_map, 
                 temperature_map = temperature_map,
                 beta = beta)
      })
    
      # Extract and format the results ----
      ## FMR
      posterior_FMR <- MC_sim |> 
        purrr::map(`[[`, "FMR") |>
        do.call(what = "cbind") # a map array for fish, a vector for others
      
      smry_FMR_map <- data.frame(
        x = map_coordinates$x,
        y = map_coordinates$y,
        FMR_mean = apply( posterior_FMR, 1, "mean"),
        FMR_sd = apply( posterior_FMR, 1, "sd"),
        FMR_L10 = apply( posterior_FMR, 1, function(i){quantile(i, probs = 0.10)}),
        FMR_U90 = apply( posterior_FMR, 1, function(i){quantile(i, probs = 0.90)})
      )
      
      ## Abundance and energyscapes
      posterior_ab <- MC_sim |> 
        purrr::map(`[[`, "abundance") |> # ou purrr::map(`[[`, 1)
        do.call(what = "cbind") # a map array for fish, a vector for others
      
      posterior_Energyscape <- MC_sim |> 
        purrr::map(`[[`, "Energyscape") |>
        do.call(what = "cbind") # an map array
      
      smry_Energyscape <- data.frame(
        x = map_coordinates$x,
        y = map_coordinates$y,
        N_mean = apply( posterior_ab, 1, "mean"),
        N_sd = apply( posterior_ab, 1, "sd"),
        N_L10 = apply( posterior_ab, 1, function(i){quantile(i, probs = 0.10)}),
        N_U90 = apply( posterior_ab, 1, function(i){quantile(i, probs = 0.90)}),
        Energyscape_mean = apply( posterior_Energyscape, 1, "mean"),
        Energyscape_sd = apply( posterior_Energyscape, 1, "sd"),
        Energyscape_L10 = apply( posterior_Energyscape, 1, function(i){quantile(i, probs = 0.10)}),
        Energyscape_U90 = apply( posterior_Energyscape, 1, function(i){quantile(i, probs = 0.90)}),
        Prey_category = levels[i],
        Predator_key = predator_name
      )
      
      ## Daily ration
      posterior_Ration <- MC_sim |> 
        purrr::map(`[[`, "daily_ration") |>
        do.call(what = "cbind") # a map array for fish, a vector for the others
      
      smry_Ration_map <- data.frame(
        x = map_coordinates$x,
        y = map_coordinates$y,
        Ration_mean = apply( posterior_Ration, 1, "mean"),
        Ration_sd = apply( posterior_Ration, 1, "sd"),
        Ration_L10 = apply( posterior_Ration, 1, function(i){quantile(i, probs = 0.10)}),
        Ration_U90 = apply( posterior_Ration, 1, function(i){quantile(i, probs = 0.90)}),
        Prey_category = levels[i],
        Predator_key = predator_name
      )
      
      smry_Ration <- data.frame(
        mean = mean(smry_Ration_map$Ration_mean),
        sd = mean(smry_Ration_map$Ration_sd),
        L10 = quantile(smry_Ration_map$Ration_L10, probs = 0.10),
        U90 = quantile(smry_Ration_map$Ration_U90, probs = 0.90),
        Prey_category = levels[i],
        Predator_key = predator_name
      )
      
      ## Daily ration prop body mass
      posterior_RationPropBM <- MC_sim |> 
        purrr::map(`[[`, "prop_body_mass") |>
        do.call(what = "cbind")
      
      smry_RationPropBM_map <- data.frame(
        x = map_coordinates$x,
        y = map_coordinates$y,
        RationPropBM_mean = apply( posterior_RationPropBM, 1, "mean"),
        RationPropBM_sd = apply( posterior_RationPropBM, 1, "sd"),
        RationPropBM_L10 = apply( posterior_RationPropBM, 1, function(i){quantile(i, probs = 0.10)}),
        RationPropBM_U90 = apply( posterior_RationPropBM, 1, function(i){quantile(i, probs = 0.90)}),
        Prey_category = levels[i],
        Predator_key = predator_name
      )
      
      smry_RationPropBM <- data.frame(
        mean = mean(smry_RationPropBM_map$RationPropBM_mean),
        sd = mean(smry_RationPropBM_map$RationPropBM_sd),
        L10 = quantile(smry_RationPropBM_map$RationPropBM_L10, probs = 0.10),
        U90 = quantile(smry_RationPropBM_map$RationPropBM_U90, probs = 0.90),
        Prey_category = levels[i],
        Predator_key = predator_name
      )
      
      # ConsoMap
      posterior_ConsoMap <- MC_sim |> 
        purrr::map(`[[`, "conso_map") |>
        do.call(what = "cbind")
      
      smry_ConsoMap_map <- data.frame(
        x = map_coordinates$x,
        y = map_coordinates$y,
        ConsoMap_mean = apply( posterior_ConsoMap, 1, "mean"),
        ConsoMap_sd = apply( posterior_ConsoMap, 1, "sd"),
        ConsoMap_L10 = apply( posterior_ConsoMap, 1, function(i){quantile(i, probs = 0.10)}),
        ConsoMap_U90 = apply( posterior_ConsoMap, 1, function(i){quantile(i, probs = 0.90)}),
        Prey_category = levels[i],
        Predator_key = predator_name
      )
      
      smry_ConsoMap <- data.frame(
        mean = sum(smry_ConsoMap_map$ConsoMap_mean),
        sd = sum(smry_ConsoMap_map$ConsoMap_sd),
        L10 = sum(smry_ConsoMap_map$ConsoMap_L10),
        U90 = sum(smry_ConsoMap_map$ConsoMap_U90),
        Prey_category = levels[i],
        Predator_key = predator_name
      )
      
      # return the result tables
      return(list(
        FMR_map = smry_FMR_map, 
        Energyscape_map = smry_Energyscape, 
        DailyRation_map = smry_Ration_map, 
        DailyRation = smry_Ration, 
        DailyRationPropBM_map = smry_RationPropBM_map, 
        DailyRationPropBM = smry_RationPropBM, 
        Conso_map = smry_ConsoMap_map, 
        Conso = smry_ConsoMap
      ))
    })
    
    message("Wrapping up")
    # wrapping tables
    smry_DailyRation <- prey_loop |> 
        purrr::map(`[[`, "DailyRation") |>
        do.call(what = "rbind") 
    smry_DailyRationPropBM <- prey_loop |> 
        purrr::map(`[[`, "DailyRationPropBM") |>
        do.call(what = "rbind") 
    smry_Conso <- prey_loop |> 
        purrr::map(`[[`, "Conso") |>
        do.call(what = "rbind") 
    
    # wrapping maps
    smry_FMR_map <- prey_loop[[1]]$FMR_map
    smry_Energyscape <- prey_loop[[1]]$Energyscape_map 
    smry_DailyRation_map <- prey_loop |> 
        purrr::map(`[[`, "DailyRation_map") |>
        do.call(what = "rbind") 
    smry_DailyRationPropBM_map <- prey_loop |> 
        purrr::map(`[[`, "DailyRationPropBM_map") |>
        do.call(what = "rbind") 
    smry_Conso_map <- prey_loop |> 
        purrr::map(`[[`, "Conso_map") |>
        do.call(what = "rbind") 
    
    return(list(
      FMR_map = smry_FMR_map, 
      Energyscape = smry_Energyscape, 
      DailyRation = smry_DailyRation, 
      DailyRationPropBM = smry_DailyRationPropBM, 
      Conso = smry_Conso,
      DailyRation_map = smry_DailyRation_map, 
      DailyRationPropBM_map = smry_DailyRationPropBM_map, 
      Conso_map = smry_Conso_map))
  }
}
